version: "3.8"

networks:
  1panel-network:
    external: true

services:
  kibana:
    image: kibana:8.14.3
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5601
    volumes:
      - "./data/conf/kibana.yml:/usr/share/kibana/config/kibana.yml"
    environment:
      - SERVER_NAME="kibana"
      - SERVER_HOST="0.0.0.0"
      - SERVER_PORT=5601
      - ELASTICSEARCH_HOSTS=${elasticsearch_hosts}
      - ELASTICSEARCH_USERNAME=${elasticsearch_username}
      - ELASTICSEARCH_PASSWORD=${elasticsearch_password}
      - I18N_LOCALE="zh-CN"
      - SERVER_SHUTDOWNTIMEOUT="5s"
      - MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true